# fly.toml app configuration file generated for pyshield on 2025-12-11T08:21:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pyshield'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = 'sqlite+aiosqlite:////data/pyshield.db'
  LOG_FILE = '/data/pyshield.log'
  PYTHONDONTWRITEBYTECODE = '1'
  PYTHONUNBUFFERED = '1'

[[mounts]]
  source = 'pyshield_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'get'
    path = '/api/v1/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
